apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bus-app
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - ptm.baeksung.kr
      secretName: ptm-baeksung-kr-tls
  rules:
    - host: ptm.baeksung.kr
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: bus-api
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bus-web
                port:
                  number: 80
